name: CI

on: [push, pull_request]

jobs:
  build:
    env:
      PYTHONPATH: yugiohbot
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
      PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip chromium-browser
          mkdir -p ~/bin
          curl -SL https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip > chromedriver.zip
          unzip chromedriver.zip -d ~/bin/
          cp -r /usr/bin/chromium-browser ~/bin/
          ls -l ~/bin
          chmod +x ~/bin/chromedriver
          chmod +x ~/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r yugiohbot/requirements.txt
          pip install pytest-cov codecov

      - name: Run Tests
        run: |
          docker run -d --name fake-gcs-server -p 4443:4443 -v $PWD/yugiohbot/tests/data:/data fsouza/fake-gcs-server
          pytest --cov=./

      - name: Report coverage
        run: codecov
